export const AUTH_COMMANDS = {
  // Demo / Health
  PING: 'PING',

  // Core Auth
  LOGIN: 'LOGIN',
  GOOGLE_LOGIN: 'GOOGLE_LOGIN',
  REGISTER: 'REGISTER',
  LOGOUT: 'LOGOUT',

  // Email Verification
  VERIFY_EMAIL: 'VERIFY_EMAIL',
  RESEND_VERIFICATION: 'RESEND_VERIFICATION',

  // Token
  REFRESH_TOKEN: 'REFRESH_TOKEN',
  VALIDATE_TOKEN: 'VALIDATE_TOKEN',

  // Password
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  RESET_PASSWORD: 'RESET_PASSWORD',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',

  // Profile
  GET_PROFILE: 'GET_PROFILE',
  DELETE_ACCOUNT: 'DELETE_ACCOUNT',
};

export const AUTH_EVENTS = {
  ACCOUNT_DELETED: 'ACCOUNT_DELETED',
};
