export const MEDIA_COMMANDS = {
  // Health
  PING: 'MEDIA_PING',

  // Metadata CRUD
  SAVE_METADATA: 'MEDIA_SAVE_METADATA',
  GET_BY_ID: 'MEDIA_GET_BY_ID',
  GET_BY_PATH: 'MEDIA_GET_BY_PATH',
  GET_LIST: 'MEDIA_GET_LIST',
  MARK_USED: 'MEDIA_MARK_USED',
  DELETE: 'MEDIA_DELETE',

  // Cleanup
  CLEANUP_ORPHANS: 'MEDIA_CLEANUP_ORPHANS',
} as const;
